### ISSUE TITLE
Could you show an example on how to use it?

### ISSUE THREAD

**Issue by pascualin** [infinitedreams9586/FindHardCodedStrings#1]
Hello, I have downloaded your script and tried to use it on my project but nothing is happening. I am new to Python so I guess the problem is on my side. Could you give some directions on how to use the script? Do I need to place the script to some specific folder or pass some specific parameters?

Thanks!

**Comment by infinitedreams9586** [comment]
Hi pascualin, iOS one or Android one?

**Comment by pascualin** [comment]
I'm trying the iOS, actually I'm adding a few improvements, I figured out how to make it run at the end! Thanks!

**Comment by infinitedreams9586** [comment]
Thanks pascualin,
I have added some comments in the script file. Just replace "HelloWorld" in the script with your project's folder name. I have changed some other stuff as well. please take latest. kindly note that resource strings will only be displayed on console.

**Comment by pascualin** [comment]
Thank you very much! I will take a look :+1:
